---
name: The Daily Binge
description: A site for reviews
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: "/"
disqus: Yym4hzTy1Y
email: siddsantham@gmail.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
